### PR TITLE
Missing data for precipitation

### LINKED ISSUE #4: NASA POWER Server not responding
If the server/web-page is not responding the package will continuously try to retrieve the data for several minutes until failing.

Add function to check server response before requesting data.

### PR DESCRIPTION
**Pull request by femiguez**
## Description

Currently, NASA POWER is not returning precipitation. It is returned as -999.0, which is not captured by the na argument in readr:read_csv. I have expanded the argument to hopefully capture a few more of these. 

## Example

I just ran the example in ?get_power with this change and it returns 'NA' instead of '-999'

### CODE REVIEW

**Comment by adamhsparks** [comment]
Hi Fernando,
Earlier in the day before you submitted this, I'd committed this change to the devel branch:
https://github.com/ropensci/nasapower/commit/62db54478d8c138969482a6d9b12ea74d75d749a

I suppose your fix is probably the better option though. I'll revert my commit and apply your PR to that branch.

**Comment by Ebedthan** [comment]
Hi @adamhsparks, 
The fixed version is not yet deployed on CRAN, I would not have understood was was going on if have not found this PR.
Please can the fixed version be submitted to CRAN?
And can you please kindly give me some details on why NASA power is not returning precipitation at the time?
Thanks

**Comment by adamhsparks** [comment]
The plan is to submit a new version to CRAN with bug fixes and other enhancements as I’ve done in the past. Since this is not a major bug, and is easily fixed by the end user, either replacing the values with a proper `NA` or installing from GitHub, it’s not a high priority at the moment. I will do that once I’m satisfied that there are no other bugs that need to be fixed and when I have the time to do it.

This is just a client for the POWER API, you need to direct questions about the data themselves to the POWER team, not to me please.

**Comment by Ebedthan** [comment]
Ooh thanks so much, @femiguez, I'll try it out!

**Pull request merged**
